version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run:
          name: install dependencies
          command: yarn install
  test:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: lint
          command: yarn lint
      - run:
          name: unit test
          command: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
